version: '3'

services:
  ros-humble:
    image: meu_ros_humble_gazebo
    command: >
      /bin/bash -c "source /opt/ros/humble/setup.bash &&
      ros2 launch turtlebot3_gazebo turtlebot3_dqn_stage1.launch.py"
    volumes:
          - /tmp/.X11-unix:/tmp/.X11-unix
          - ./:/root/dev_ws
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
      - "TURTLEBOT3_MODEL=burger"
    network_mode: host
    security_opt:
      - seccomp:unconfined
    devices:
      - "/dev/dri:/dev/dri"
    privileged: true
    restart: unless-stopped