version: '3'
services:
  ros-foxy:
    image: ros-foxy-gazebo # O nome da imagem que você construiu
    container_name: meu_container_ros
    environment:
      - DISPLAY=${DISPLAY} # Substitua com o display correto, se necessário
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # Para a interface gráfica, se necessário
      - ./:/root/workspace # Mapeia o diretório atual para o workspace dentro do container
    network_mode: host
    security_opt:
      - seccomp:unconfined # Opções de segurança, pode ser necessário para o Gazebo
    privileged: true # Rodar o container em modo privilegiado para acesso completo ao host
    command: bash -c "source /opt/ros/foxy/setup.bash && gazebo" # Comando inicial
