version: '3'

services:
  meu_ros_foxy:
    build: .
    image: meu_ros_foxy_gazebo:latest
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    security_opt:
      - seccomp:unconfined
    devices:
      - "/dev/dri:/dev/dri"
    privileged: true
    restart: unless-stopped
