version: '3'

services:
  ros-foxy:
    image: ros-foxy-gazebo # Certifique-se de que esta imagem tem tudo instalado para o Turtlebot3 e o Gazebo
    container_name: meu_container_ros
    environment:
      - DISPLAY=${DISPLAY} # Substitua com o display correto, se necess치rio
      - "TURTLEBOT3_MODEL=burger" 
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # Para a interface gr치fica
      - ./:/root/workspace # Mapeia o diret칩rio atual para o workspace dentro do container
    network_mode: host
    security_opt:
      - seccomp:unconfined # Pode ser necess치rio para o Gazebo
    privileged: true # Modo privilegiado para acesso ao host
    command: >
      /bin/bash -c "source /opt/ros/foxy/setup.bash && 
      ros2 launch turtlebot3_gazebo turtlebot3_dqn_stage1.launch.py"
